services:
  andymobiles:
    container_name: andymobile-backend
    restart:  always
    image: node:20.10.0
    ports:
      - 4002:4002
    volumes:
      - .:/usr/src/andymobile
    working_dir:  /usr/src/andymobile
    networks:
      - andymobile_network
    # PRODUCTION
    command: bash -c "npm install && npm run start:prod"

networks:
  andymobile_network:
    driver: bridge